### ISSUE TITLE
day, hour, second - Units that are not "closed" are not working. 

### ISSUE THREAD

**Issue by laksefest** [amicks/Speculator#11]
Is there any point of having day, hour, second available, when they do not have a "closed" value? Cause they all seem to produce an error. Or should they take the last available timestamp? For example, if you do this, you get an error:

$ python main.py --unit hour
Traceback (most recent call last):
  File "main.py", line 106, in <module>
    raise SystemExit(main())
  File "main.py", line 82, in main
    x = x.drop(['close'], axis=1)
  File "/home/anaconda3/envs/speculator/lib/python3.6/site-packages/pandas/core/generic.py", line 2530, 
in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/home/anaconda3/envs/speculator/lib/python3.6/site-packages/pandas/core/generic.py", line 2562, 
in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/home/anaconda3/envs/speculator/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3
741, in drop
    labels[mask])
ValueError: labels ['close'] not contained in axis

**Comment by amicks** [comment]
I'll look into it.  If there is no close then it should use the most current price.  I wasn't aware that Poloniex API didn't return a close for every date.

**Comment by amicks** [comment]
This was expected behavior.  By default, the partition size is 14.  Poloniex returned only 7 objects (dates with stats) where each did have a 'close' attribute.  You can't make partitions of 14 with size 7.    

You can change the partition with the '-pn _PARTITION_SIZE_' program argument.  Additionally, another way to get around this is by changing the number of objects per unit with the '-count _COUNT_' program argument.  Sometimes, despite changing the count argument, Poloniex API does not return enough objects to do a ML model on.  This is a constraint on Poloniex and offers a more compelling reason to integrate another crypto market API.

I added an exception to make this more clear if you come across it.  I also added assertions and fixed an error when the partitions were too low for the response.

If you feel this issue was resolved, please close it.  If not, or you have any other related feedback, feel free to reply.  Thanks!
